import unittest

from Exercice_4_1_ComputingTheParityOfAWord import Test_4_1_ComputingTheParityOfAWord
from Exercice_6_1_InterconvertStringsAndIntegers import Test_6_1_InterconvertStringsAndIntegers
from Exercice_7_1_MergingTwoSortedLists import Test_7_1_MergingTwoSortedLists
from Exercice_7_2_InversingASubList import Test_7_2_InversingASubList
from Exercice_7_7_RemovingThekthLatestNode import  Test_7_7_RemovingThekthLatestNode
from Exercice_7_10_OddEvenAlgo import  Test_7_10_OddEvenAlgo

Test_4_1_ComputingTheParityOfAWord()
Test_6_1_InterconvertStringsAndIntegers()
Test_7_1_MergingTwoSortedLists()
Test_7_2_InversingASubList()
Test_7_7_RemovingThekthLatestNode()
Test_7_10_OddEvenAlgo()


if __name__ == "__main__":
    unittest.main()
